export const flex_styles = {
    row_center: {
        display:'flex',
        flexDirection:'row',
        justifyContent:'center'
    },
    col_center:{
        display:'flex',
        flexDirection:'column',
        justifyContent:'center'
    },
    row_right:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'right'
    },
    row_left:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'left'
    },
    col_down:{
        display:'flex',
        flexDirection:'column',
        justifyContent:'right'
    },
    col_up:{
        display:'flex',
        flexDirection:'column',
        justifyContent:'left'
    }
};
